version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - backend/.env
    environment:
      - DATABASE_URL=sqlite:////data/app.db
      - JWT_SECRET=${JWT_SECRET:-dev_secret_change_me}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-}
    volumes:
      - backend_data:/data
    ports:
      - "8000:8000"
    restart: unless-stopped

  # Optional Postgres for production-like dev
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=checkout
      - POSTGRES_PASSWORD=checkout
      - POSTGRES_DB=checkout
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  backend_data:
  pg_data:

